# Generated by Django 3.2.5 on 2021-07-10 18:17

from django.db import migrations, models

import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='수정일')),
                ('deleted_yn', models.CharField(blank=True, default=0, max_length=1, null=True, verbose_name='삭제여부')),
                ('email', models.EmailField(max_length=80, unique=True, verbose_name='이메일')),
                ('nickname', models.CharField(max_length=50, verbose_name='닉네임')),
                ('age', models.IntegerField(blank=True, verbose_name='나이')),
                ('phone', models.CharField(blank=True, max_length=13, verbose_name='핸드폰번호')),
                ('position', models.CharField(blank=True, max_length=10, verbose_name='포지션')),
                ('profile_image', models.ImageField(blank=True, help_text='48px * 48px 크기의 png/jpg 파일을 업로드해주세요.', upload_to='accounts/profile/%Y/%m/%d', verbose_name='이미지경로')),
                ('password', models.CharField(max_length=128, verbose_name='비밀번호')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '유저',
                'db_table': 'user',
            },
            managers=[
                ('objects', user.models.UserManager()),
            ],
        ),
    ]
